// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function CreateDatabase():Promise<string>;

export function CreateNewCategory(arg1:string):Promise<string>;

export function CreateNewGame(arg1:string,arg2:string,arg3:Array<number>):Promise<string>;

export function EditCategory(arg1:number,arg2:string):Promise<string>;

export function EraseCategory(arg1:number):Promise<string>;

export function EraseGame(arg1:number):Promise<void>;

export function IsDev():Promise<boolean>;

export function LoadAllCategories():Promise<Array<database.Category>>;

export function LoadCategories(arg1:number,arg2:number):Promise<Array<database.Category>>;

export function LoadCategoryName(arg1:number):Promise<string>;

export function LoadGames(arg1:number,arg2:number):Promise<Array<database.Game>>;

export function SelectImageFolder():Promise<string>;

export function SetDatabase():Promise<string>;
