// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDatabase() {
  return window['go']['app']['App']['CreateDatabase']();
}

export function CreateNewCategory(arg1) {
  return window['go']['app']['App']['CreateNewCategory'](arg1);
}

export function EraseCategory(arg1) {
  return window['go']['app']['App']['EraseCategory'](arg1);
}

export function LoadCategories(arg1, arg2) {
  return window['go']['app']['App']['LoadCategories'](arg1, arg2);
}

export function SelectImageFolder() {
  return window['go']['app']['App']['SelectImageFolder']();
}

export function SetDatabase() {
  return window['go']['app']['App']['SetDatabase']();
}
