// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDatabase() {
  return window['go']['app']['App']['CreateDatabase']();
}

export function SelectImageFolder() {
  return window['go']['app']['App']['SelectImageFolder']();
}

export function SetDatabase() {
  return window['go']['app']['App']['SetDatabase']();
}
