// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDatabase() {
  return window['go']['app']['App']['CreateDatabase']();
}

export function CreateNewCategory(arg1) {
  return window['go']['app']['App']['CreateNewCategory'](arg1);
}

export function CreateNewGame(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateNewGame'](arg1, arg2, arg3);
}

export function EditCategory(arg1, arg2) {
  return window['go']['app']['App']['EditCategory'](arg1, arg2);
}

export function EraseCategory(arg1) {
  return window['go']['app']['App']['EraseCategory'](arg1);
}

export function EraseGame(arg1) {
  return window['go']['app']['App']['EraseGame'](arg1);
}

export function IsDev() {
  return window['go']['app']['App']['IsDev']();
}

export function LoadAllCategories() {
  return window['go']['app']['App']['LoadAllCategories']();
}

export function LoadCategories(arg1, arg2) {
  return window['go']['app']['App']['LoadCategories'](arg1, arg2);
}

export function LoadCategoryName(arg1) {
  return window['go']['app']['App']['LoadCategoryName'](arg1);
}

export function LoadGames(arg1, arg2) {
  return window['go']['app']['App']['LoadGames'](arg1, arg2);
}

export function SelectImageFolder() {
  return window['go']['app']['App']['SelectImageFolder']();
}

export function SetDatabase() {
  return window['go']['app']['App']['SetDatabase']();
}
