// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function CreateDatabase():Promise<string>;

export function CreateNewCategory(arg1:string):Promise<string>;

export function EraseCategory(arg1:number):Promise<string>;

export function IsDev():Promise<boolean>;

export function LoadCategories(arg1:number,arg2:number):Promise<Array<database.Category>>;

export function SelectImageFolder():Promise<string>;

export function SetDatabase():Promise<string>;
