// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDatabase() {
  return window['go']['main']['App']['CreateDatabase']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetDatabase() {
  return window['go']['main']['App']['SetDatabase']();
}
